<html>
    <head>
        <meta charset="utf-8">
        <title>Contact Formulier</title>
    </head>
    <body>
        <main style="font-family:arial;">
          <h1>Heeft u een suggestie? Stuur ons een bericht!</h1>
           <form class="contact-form" action="?controller=contact&action=contactform" method="post">
            <input type ="text" name="name" placeholder="Full Name"><br>
            <input type ="text" name="mail" placeholder="E-mail"><br>
            <textarea style="resize: none;" name="Suggestion" placeholder="Schrijf hier uw suggestie" cols="45" rows="5"></textarea><br>
            <button type="submit" name="submit">Stuur bericht</button>
           </form>
</html>