<LINK href="./content/products.css" rel="stylesheet" type="text/css">
<html>
    <head>
        <meta charset="utf-8">
        <title>Contact Formulier</title>
    </head>
    <body>
        <main>
          <h1>Hartelijk bedankt voor uw bericht. Uw feedback is erg belangrijk voor ons!</h1><br>
          <p>Klik op deze knop om terug te gaan naar het productoverzicht.</p>
<button onclick="goBack()">Terug naar het productoverzicht</button>

<script>
function goBack() {
  window.history.go(-2);
}
</script>

</html>