<html>
    <head>
        <meta charset="utf-8">
        <title>Contact Formulier</title>
    </head>
    <body>
        <main>
          <h1>Hartelijk bedankt voor uw bericht. Uw feedback is erg belangrijk voor ons!</h1><br>
          <p>Klik op deze knop om terug te gaan naar het productoverzicht.</p>
          <form action="http://localhost/wwi/?controller=products&action=products">
    <input type="submit" value="Terug naar het productoverzicht" />
</form>


</html>