<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

/* Style the header */
header {
  background-color: #666;

  text-align: center;
  font-size: 30px;
  color: white;
}

/* Container for flexboxes */
section {
  display: -webkit-flex;
  display: flex;
}

article {
  -webkit-flex: 3;
  -ms-flex: 3;
  flex: 3;
  background-color: #f1f1f1;
  padding: 10px;
}

.article1 {
width: 200px; 
font-family: arial; 
font-size: 16px; 
border: 1px solid black; 
text-align:center;  
margin:20px; 
position: relative;
left: 5px;
right: 1px;
}

.titel {
  height: 60px;
  background-color: darkbrown;
  color: black;
  font-family: Arial;
  line-height: 2;
}

.protitle {
  height: 475px;
  width: 350px;
}

.button1 {

  position: relative;
margin: 20px;
  color: black;
  font-size: 16px;
  font-family: arial;
  border-radius: 12px;
  text-align: center;

}

.button1:hover {
    background-color: #e7e7e7;
}

.buttondiv {
  width: 275px;
  Height: 85px;
  position: relative;
  left: 22px;
  top: 25px;
}

.logodiv {
  position: relative;
  left: 5px;
}

textfield {
  width: 100%;
  height: 150px;
  padding: 12px 20px;
  box-sizing: border-box;
  border-radius: 4px;
  background-color: clear;
  font-size: 16px;
  font-family: arial;
  resize: none;
}

.product {
  width:450px;
  height: 540px;
  margin: 30px;
  position: relative;
  top: 125px;
  position: relative; 
  top: 50px;
  right: 20px;
  font-family: arial;
}


.description {
  height:38px; 
  width:323px; 
  font-family: arial; 
  font-size: 16px; 
  text-align: center; 
  line-height: 2.4;
}

*{
    margin: 0;
    padding: 0;
}
.rate {
    float: left;
    height: 46px;
    padding: 0 10px;
}
.rate:not(:checked) > input {
    position:absolute;
    top:-9999px;
}
.rate:not(:checked) > label {
    float:right;
    width:1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:30px;
    color:#ccc;
}
.rate:not(:checked) > label:before {
    content: '★ ';
}
.rate > input:checked ~ label {
    color: #ffc700;    
}
.rate:not(:checked) > label:hover,
.rate:not(:checked) > label:hover ~ label {
    color: #deb217;  
}
.rate > input:checked + label:hover,
.rate > input:checked + label:hover ~ label,
.rate > input:checked ~ label:hover,
.rate > input:checked ~ label:hover ~ label,
.rate > label:hover ~ input:checked ~ label {
    color: #c59b08;
}

.titel2 {
  width: 400px;
  font-size: 18px;
  font-family: arial;
  line-height: 3.0;
  color: white;
  background-color: DarkBlue;
  border-radius: 25px;
  margin: 12px;
}

.rate {
  height: 60px;
  position: relative;
  line-height: 1.7;
}

.logodiv {
  width: 275px;
}

.welkom {
  position: relative;
  float: right;
  right: 50px;
  top: 100px;
  font-family: arial;
  width: 600px;
}

</style>

</head>

<body>
<header style="height: 100%;">
  <div style="width: 700px;"></div>
    <div class="titel">Homepage</div>
      <div class="titel2" style="float: right;">Beoordeel onze webshop! 
      <div class="rank" style="float:right;"> 
      <div class="rate">
      <input type="radio" id="star5" name="rate" value="5" />
      <label for="star5" title="text">5 stars</label>
      <input type="radio" id="star4" name="rate" value="4" />
      <label for="star4" title="text">4 stars</label>
      <input type="radio" id="star3" name="rate" value="3" />
      <label for="star3" title="text">3 stars</label>
      <input type="radio" id="star2" name="rate" value="2" />
      <label for="star2" title="text">2 stars</label>
      <input type="radio" id="star1" name="rate" value="1" />
      <label for="star1" title="text">1 star</label>
    </div>
    </div>
    </div>
  </div>
</header>
<div style="height: 1200px;">
<div style="position: relative; top: 20px; height: 50px; width: 400px; font-family:arial; left: 160px;">  <h2>Nieuw in ons assortiment!</h2>
</div>


  <?php foreach(array_slice($queryresult, 0, 2) as $product ): ?>
    <div class="product" style="width: 275px; height: 340px; float:left; border: 2px solid;">
    <div class="imagebox" style="witdh: 100px; height: 300px; background-color:white;">
      <article class="article1"><?php  echo $product["stockitemname"];?> </article> 
        <div class="Logodiv">
        <?php if (strlen($product["Photo"]) > 0) { ?>
                <img src="data:image/png;base64,<?php echo base64_encode( $product["Photo"] ); ?>" />
                <?php } else { ?>
                <img src="content/Geen_afbeelding1.png" style="position: relative; left: 35px;"/>
                <?php } ?>  
        </div>
        <div class="buttondiv">    
         <form action="?controller=productdetail&action=productdetail&ID=97" method="POST">
            <button style="margin: 20px; width: 180px; height: 45px;"class="button1">Klik om te bekijken</button>
          </form>      
        </div>
      </div>
    </div>
  <?php endforeach; ?>


    <div class="welkom">
      <form>
        <h2><b>Welkom op de webshop van Wide World Importers!</b></h2></br>
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
</form>
    </div>
  </div>
</div>

</div>


</body>
