<Style>
body{
background-image: url("reg.jpg");
background-color: #ADD8E6;
}

.button {
  font: bold 11px Arial;
  text-decoration: none;
  background-color: #EEEEEE;
  color: #333333;
  padding: 2px 6px 2px 6px;
  border-top: 1px solid #CCCCCC;
  border-right: 1px solid #333333;
  border-bottom: 1px solid #333333;
  border-left: 1px solid #CCCCCC;
}
</style>
<h1>Controleer u gegevens</h1>
<div style = "
    height: 200px;
    position: absolute;
    top:0;
    bottom: 0;
    left: 0;
    right: 0;

    margin: auto;" class="winkelmand">
    
<table>
    <tr>
        <td>  
            <label>Volledige naam</label>
        </td>
        <td>
        <input type="text" value="<?php echo $result[0]['FullName']?>">
    </td>
    </tr>
        <tr>      
            <td>
            <label>Straat + Huisnummer</label>
            </td>
            <td>
                <input type="text" value="<?php echo $result[0]['AdressLine']?>">  
            </td>       
        </tr>
    <tr>
        <td>
            <label>Postcode</label>  
        </td>
        <td>
            <input type="text" value="<?php echo $result[0]['PostalCode']?>">
        </td>
    </tr>
    <tr>
    <tr>
        <td>  
            <label>Stad</label>  
        </td>
        <td>
            <input type="text" value="<?php echo $result[0]['City']?>">
        </td>  
    </tr>
    <tr>
        <td>  
        <label>Telefoon</label>  
        </td>
        <td>
            <input type="text" value="<?php echo $result[0]['PhoneNumber']?>">
        </td>      
    </tr> 
    <tr>
    <Td>
    <?php $totaal = $_SESSION['TotalPrice']; if($totaal >= 50){ $costs = "gratis";}else{ $costs = "€2.50"; $totaal = $totaal + 2.50;} ?>
    Verzend kosten : <?php echo $costs ?>
    <tr>
    <td>
            Totaal prijs: €<?php echo $totaal?>
    </td>
    </tr>
    <tr>
    <td>
    <input type="radio" name="Ideal" value="Ideal"> Ideal
    </td>
    </tr>
    <tr>
    <td>
    <input type="radio" name="Ideal" value="Ideal"> Paypal(not available)<br>
    </td>
    </tr> 
</table>
<Table>

</table>
<a class="button" href="?controller=Basket&action=winkelmand">Back</a>
<a class="button" href="?controller=Basket&action=Payment">Bevestigen</a>

</div>
