<html>
<body>

<h2>Login</h2>
<?php 
echo $reslt;
?>
<form action="?controller=login&action=login" method="post">
<label for="e-mail"><b>E-mail:</b></label>
    <input type="text" placeholder="uw e-mail" name="e-mail" required>

    <label for="psw"><b>Wachtwoord:</b></label>
    <input type="password" placeholder="uw wachtwoord" name="psw" required>
        
    <button type="submit">Login</button>
    
</form> 

</body>
</html>