<html>
<head></head>

<body>
<?php
if(isset($_SESSION['auth']) && $_SESSION['auth'] == "true")
{
?>
already logged in
<?php

}else
{
?>
<form method="post" action="?controller=login&action=invoke">
    <input type="text" placeholer="email" name="Email" id="Email" value="">
    <input type="text" name="Password" id="Password" value="">
        
    <input type="submit" value="inloggen" />
</form>
<?php


}
?>
</body>
</html>