<div style = "
    width: 200px;
    height: 200px;
    position: absolute;
    top:0;
    bottom: 0;
    left: 0;
    right: 0;

    margin: auto;" class="succes">

    <h1>Er is iets fout gegaan. Probeer het opnieuw</h1>
    <body>
    <a href="?controller=content&action=home">Terug naar de Homepage!
    </body>
    
    </div>

    <?php $winkelmand = null;

$_SESSION['winkelmand'] = $winkelmand;
 ?>