<head>
<LINK href="./content/style.css" rel="stylesheet" type="text/css">
</head>
<div class ="titledetail">
    <h2><?php echo $result["stockitemname"] ?></h2>
</div>
<div class="productspec"  style="font-family:arial;>
<table class="test>
<table class="productspec2">
    <tr><th><?php if (strlen($result["Photo"]) > 0) { ?>
                <img src="data:image/png;base64,<?php echo base64_encode( $result["Photo"] ); ?>" />
                <?php } else { ?>
                <img src="content/geen_afbeelding.png"/>
                <?php } ?></th><td></td></tr> 
                <br>
<tr><th><a class="lightbox" href="#photo2">
<?php if (strlen($result["Photo2"]) > 0) { ?>
                <img src="data:image/png;base64,<?php echo base64_encode( $result["Photo2"] ); ?>" />
                <?php } else { ?>
                <img src="content/geen_afbeelding.png"/>
                <?php } ?>  
</a> 
<div class="lightbox-target" id="photo2">
<?php if (strlen($result["Photo2"]) > 0) { ?>
                <img src="data:image/png;base64,<?php echo base64_encode( $result["Photo2"] ); ?>" />
                <?php } else { ?>
                <img src="content/geen_afbeelding.png"/>
                <?php } ?>  
   <a class="lightbox-close" href="#"></a>
</div>
                </th>
<td><a class="lightbox" href="#photo3">
<?php if (strlen($result["Photo3"]) > 0) { ?>
                <img src="data:image/png;base64,<?php echo base64_encode( $result["Photo3"] ); ?>" />
                <?php } else { ?>
                <img src="content/geen_afbeelding.png"/>
                <?php } ?>  
</a> 
<div class="lightbox-target" id="photo3">
<?php if (strlen($result["Photo3"]) > 0) { ?>
                <img src="data:image/png;base64,<?php echo base64_encode( $result["Photo3"] ); ?>" />
                <?php } else { ?>
                <img src="content/geen_afbeelding.png"/>
                <?php } ?>  
   <a class="lightbox-close" href="#"></a>
</div>
                </td></tr>

                <br>
</th>
    <tr><th>Productspecificaties :</th>
<br>
    <tr><th>Beschrijving</th><td><?php echo $result["marketingcomments"] ; ?></td></tr><br>
    
    <tr><th>Voorraad</th><td><?php
if ($result["QuantityOnHand"] > "999") {
    echo 'Meer dan 1000! <img src="Content/ggroen-vinkje.png" alt="vinkje"> ';
} elseif ($result["QuantityOnHand"] > "0") {
    echo 'Minder dan 1000! <img src="Content/groen-vinkje.png" alt="vinkje">';
} else {
    echo 'Product uitverkocht! <img src="Content/rood-kruis.png" alt="kruis">';
}
?></td></tr><br>
    <tr><th>Prijs</th><td>€ <?php echo $result["unitprice"] ; ?> Incl. Btw</td></tr>
    <tr><th><form action="?controller=products&action=winkelmand" method="POST"><input type="hidden" name="product" value="<?php echo $result["stockitemid"] ; ?>"/>
    <tr><th>Aantal :<input type="number" name="amount" value="1" style="width:50px;border:1px solid"/><td><div class="button"><button type="submit">In winkelwagen</button></form></div></td></tr>
</table>

</div>
<div class="video-container">
    <iframe width="426" height="240" src="<?php echo $result["videourl"] ; ?>" frameborder="0" allowfullscreen></iframe></div>
</div>


