<LINK href="./content/products.css" rel="stylesheet" type="text/css">


<style>
/* Style the header */
header {
  background-color: #666;
  text-align: center;
  font-size: 30px;
  color: white;
}
/* Container for flexboxes */
section { 
  display: -webkit-flex;
  display: flex;
}
.titel {
  height: 60px;
  background-color: darkbrown;
  color: black;
  font-family: Arial;
  line-height: 2;
}
.reactie {
  height: 40px;
  width: 460px;
  text-align: center;
  position: relative;
  margin: 20px;
  float:right; 
  Font-family:arial; 
  border: 1px solid;
  padding-top: 20px;
}
</style>

<header style="height: 100%;">
  <div style="width: 700px;"></div>
    <div class="titel">Product overzicht</div>
</header>

<div class="reactie"> <b>Product niet aanwezig? Laat een bericht achter!</b>
  <a href="?controller=contact&action=contactformulier" >Versturen &raquo;</a>
</div>

<table class="products">
  <?php foreach ($result as $product) : ?>
    <tr class="product" style="font-family:arial;">
    <td>
    <?php if (strlen($product["Photo"]) > 0) { ?>
    <img src="data:image/png;base64,<?php echo base64_encode( $product["Photo"] ); ?>" />
    <?php } else { ?>
    <img src="content/geen_afbeelding.png"/>
    <?php } ?>
    </td>
    <td class="product-title">
    <a href="?controller=productdetail&action=productdetail&ID=<?php echo $product["stockitemid"] ; ?>"><?php echo $product["stockitemname"]; ?></a></td>
    <td> € <?php echo $product["unitprice"] ; ?>
    </td>
    <td><form action="?controller=products&action=winkelmand" method="POST"><input type="hidden" name="product" value="<?php echo $product["stockitemid"] ; ?>"/>
    Aantal :<input type="number" name="amount" value="1" style="width:50px;border:1px solid"/>&nbsp;<button type="submit">In winkelwagen</button>
    </form>
    </td>
    </tr>
<?php endforeach; ?>
<tfoot>
      <tr class="pager"><td colspan="4"><?php for ($i = 0; $i < $total; $i++) {
        $label = ($i + 1);
        $search = "";
        if (isset($_POST["search"])) $search = $_POST["search"];
        if (isset($_GET["search"])) $search = $_GET["search"];
        if ((!isset($_GET["page"]) && $i == 0) || (isset($_GET["page"]) && $i == $_GET["page"])) {
          echo "<span>$label</span>";
        } else { echo "<a href='?controller=products&action=products&search=$search&page=$i'>$label</a>"; } } ?>
      </td></tr>
</tfoot>
</table>