<div class ="titledetail">
    <h2><?php echo $result["stockitemname"] ?></h2>
</div>
<div class="productspec">

<table class="productspec2">
    <tr><th><?php if (strlen($result["Photo"]) > 0) { ?>
                <img src="data:image/png;base64,<?php echo base64_encode( $product["Photo"] ); ?>" />
                <?php } else { ?>
                <img src="content/geen_afbeelding.png"/>
                <?php } ?></th><td></td></tr> 
<tr><th></th>
    <tr><th>Productspecificaties :</th>
<tr><th></th>
<tr><th></th>
    <tr><th>Beschrijving</th><td><?php echo $result["marketingcomments"] ; ?></td></tr>
    <tr><th>Leverancier</th><td><?php echo $result["suppliername"] ; ?></td></tr>
    
    <tr><th>Prijs</th><td>€ <?php echo $result["unitprice"] ; ?> Incl. Btw</td></tr>
    <tr><th><form action="?controller=products&action=winkelmand" method="POST"><input type="hidden" name="product" value="<?php echo $product["stockitemid"] ; ?>"/>
    Aantal :<input type="number" name="amount" value="1" style="width:50px;border:1px solid"/><td><button type="submit">In winkelwagen</button></form></td></tr>
    
</table>
</div>
<div class="video-container">
    <iframe width="426" height="240" src="https://www.youtube.com/embed/j8xAeBOAC8U" frameborder="0" allowfullscreen></iframe></div>

        