<html>
<head>
  <title>Registreren</title>
</head>
<body>
  <div class="header">
  	<h2>Registreer</h2>
  </div>
	
  <form method="post" action="?controller=registratie&action=storeData">
  	<div class="input-group">
  	  <label>Gebruikersnaam:</label>
  	  <input type="text" name="Email" placeholder="Email">
  	</div>
  	<div class="input-group">
  	  <label>Wachtwoord:</label>
  	  <input type="password" name="wachtwoord" placeholder="Wachtwoord">
  	</div>
  	<div class="input-group">
  	  <button type="submit" class="btn" name="registreeruser">Registreer!</button>
  	</div>
  	<p>
  		Al een account? <a href="login.php">Log hier in!</a>
  	</p>
  </form>
</body>
</html>