<html>
<head>
  <title>Registreren</title>
  <LINK href="./content/registratie.css" rel="stylesheet" type="text/css">
</head>
<body>
  <div class="header">
  	<h2>Registreer</h2>
  </div>
	
  <form method="post" action="?controller=registratie&action=StoreData">
  	<div class="input-group">
  	  <label>E-mail:</label>
  	  <input type="email" name="Email" placeholder="E-mail" require>
  	</div>
  	<div class="input-group">
  	  <label>Wachtwoord:</label>
  	  <input type="password" name="password" placeholder="Wachtwoord" require>
  	</div>
  	<div class="input-group">
  	  <button type="submit" class="btn" name="registreeruser">Registreer!</button>
  	</div>
  	<p>
  		Al een account? <a href="?controller=login&action=invoke">Log hier in!</a>
  	</p>
  </form>
</body>
</html>