<html>
<head>
  <title>Registreren</title>
  <LINK href="./content/registratie.css" rel="stylesheet" type="text/css">
</head>
<body>
  <div class="header" style="font-family:arial;">
  	<h2>Registreer</h2>
  </div>
	
  <form method="post" action="?controller=registratie&action=StoreData">
  	<div class="input-group" style="font-family:arial; position:relative; right:24px;">
  	  <label><b>E-mail:</b></label>
  	  <input type="email" name="Email" placeholder="E-mail" require>
  	</div>
  	<div class="input-group" style="font-family:arial; position:relative; right:48px;">
  	  <label><b>Wachtwoord:</b></label>
  	  <input type="password" name="password" placeholder="Wachtwoord" require>
  	</div>
		<div class="input-group" style="font-family:arial; position:relative; right:48px;">
  	  <label><b>Voornaam:</b></label>
  	  <input type="text" name="voornaam" placeholder="Voornaam" require>
			<label><b>Achternaam:</b></label>
  	  <input type="text" name="achternaam" placeholder="Achternaam" require>
  	</div>
		<div class="input-group" style="font-family:arial; position:relative; right:48px;">
  	  <label><b>Adres + Huisnummer:</b></label>
  	  <input type="text" name="adres" placeholder="Adres" require>
			<label><b>Postcode:</b></label>
  	  <input type="text" name="postcode" placeholder="Postcode" require>
  	</div>
		<div class="input-group" style="font-family:arial; position:relative; right:48px;">
  	  <label><b>Stad:</b></label>
  	  <input type="text" name="stad" placeholder="Stad" require>
  	</div>
		<div class="input-group" style="font-family:arial; position:relative; right:48px;">
  	  <label><b>Telefoonnummer:</b></label>
  	  <input type="tel" name="telefoon" placeholder="Telefoonummer">
  	</div>
	  <div class="input-group" style="font-family:arial; ">
  	  <button style="font-family:arial;" type="submit" class="btn" name="registreeruser">Registreren</button>
  	</div>
  	<p style="font-family:arial; position: relative; left: 43%;">
  		Al een account? <a href="?controller=login&action=invoke">Log hier in!</a>
  	</p>
  </form>
</body>
</html>