<Style>
body{
background-image: url("reg.jpg");
background-color: #ADD8E6;
}


.button {
  font: bold 11px Arial;
  text-decoration: none;
  background-color: #EEEEEE;
  color: #333333;
  padding: 2px 6px 2px 6px;
  border-top: 1px solid #CCCCCC;
  border-right: 1px solid #333333;
  border-bottom: 1px solid #333333;
  border-left: 1px solid #CCCCCC;
  float: right;
}
</style>
<div style = "width: 1000px;
    height: 100px;
    position: absolute;
    top:0;
    bottom: 0;
    left: 0;
    right: 0;

    margin: auto;" class="winkelmand">
    <table>
<?php $totaal = 0;
     foreach ($mergedArrays as $product) : ?>
    <tr style="" class="basketproduct">
    <Td><img src="<?php $product['photo'] ?>"></td>
    <td><?php echo $product['stockitemname']?></td>
    
    <td>Prijs: €<?php echo $product['unitprice']?></td>
    <td>hoeveelheid: <input type='number' value = <?php echo $product['amount']?>> </td> 
    </tr>
    <?php $totaal = $product['unitprice'] * $product['amount'] + $totaal; $_SESSION['TotalPrice'] = $totaal;?>
    <?php endforeach; ?>
    <tr>
    <td>
    <?php if($totaal >= 50){ $costs = "gratis";}else{ $costs = "€2.50"; $totaal = $totaal + 2.50;} ?>
    Verzend kosten : <?php echo $costs ?>
    </td>
    </tr>
    <tr>
    <td>
    Totaal: €<?php echo $totaal; ?>
    </td>
    </tr>
    </td>
    
</table>
<button>opslaan</button>
<a class="button" href="?controller=Basket&action=Info">Continue</a>

</div>
