<!DOCTYPE html>
<html>
<?php

include './controllers/dbh-search.php';

?>
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WWI</title>
    <LINK href="./content/style.css" rel="stylesheet" type="text/css">
    
</head>

    <body>           
   
    <div id="menubar" style="height: 110px;">
         <ul>
                <li><img style="height:110px; width:170px;" class="logo" src="https://media.viva.nl/m/athrgyvwgh5t_featured_image_article.jpg/chocola.jpg"></li>
                <li><A href="?controller=content&action=home">Home</A></li>
                <li><a href="?controller=content&action=products">Producten</a></li>
                <li><a href="?controller=content&action=login">Inloggen</a></li>
                <li><a href="?controller=content&action=winkelmand">Winkelmand</a></li>
                <li><div style="font-family: arial;" class="search-container">
                <form action="views/search.phtml"> Zoek product
                <input  type="text" name="search"> <button style="width: 60px; height: 25px;"class="searchbutton">Zoek</button>
                 </form>
                </div></li>
        </ul>
    </div>



    <div id="content">
               
    </div>

    <div style="background: black" class="footer">
        <p>dit moet nog anders worden`joh no shit sherlock</p>
    </div>

</body>
</html>
