<!DOCTYPE html>
<html>

<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WWI</title>
    <LINK href="./content/style.css" rel="stylesheet" type="text/css">
    
</head>

    <body>           
        <div id="menubar" style="height: 110px;">
            <ul>
                <li><img style="height:90px; width:120px;" class="logo" src="http://5.157.81.93/Archi/www.referentiearchitectuur.nl/logos/archixl-logo.png"></li>
                <li><A href="?controller=content&action=home">Home</A></li>
                <li><a href="?controller=products&action=products">Producten</a></li>
                <?php if(isset($_SESSION['auth']) && $_SESSION['auth'] == "true"){
                    ?>
                <li><a href="?controller=login&action=logoff">Uitloggen</a></li>

                    <?php
                }else{
                    ?>
                    <li><a href="?controller=login&action=invoke">Inloggen</a></li>
                    <li><a href="?controller=registratie&action=registratie">Registreren</a></li>
                    <?php

                } ?>
                <li><a href="?controller=Basket&action=winkelmand">Winkelmand</a></li>
                
                
                <form action="?controller=products&action=products" method="POST" style="color:white; float: right; font-family: Arial; padding-top: 45px; padding-right: 130px; padding-left: 80px;">Zoek product <input type="text" name="search" class="search"/><input type="submit" value="Zoeken"/>
                </form>
            </ul>
        </div>
    </body>


    <div id="content">
               <!-- Content uit controller via require_once() -->
    </div>
 